export interface Problem {
  letter: string;
  name: string;
}

export interface Sheet {
  id: string;
  name: string;
  contestId: string;
  problems: Problem[];
}


export const CURRICULUM: Sheet[] = [
  {
    id: "sheet-1",
    name: "01. Sheet #1 (Data type - Conditions)",
    contestId: "219158",
    problems: [
      { letter: "A", name: "Say Hello With C++" },
      { letter: "B", name: "Basic Data Types" },
      { letter: "C", name: "Simple Calculator" },
      { letter: "D", name: "Difference" },
      { letter: "E", name: "Area of a Circle" },
      { letter: "F", name: "Digits Summation" },
      { letter: "G", name: "Summation from 1 to N" },
      { letter: "H", name: "Two numbers" },
      { letter: "I", name: "Welcome for you with Conditions" },
      { letter: "J", name: "Multiples" },
      { letter: "K", name: "Max and Min" },
      { letter: "L", name: "The Brothers" },
      { letter: "M", name: "Capital or Small or Digit" },
      { letter: "N", name: "Char" },
      { letter: "O", name: "Calculator" },
      { letter: "P", name: "First digit !" },
      { letter: "Q", name: "Coordinates of a Point" },
      { letter: "R", name: "Age in Days" },
      { letter: "S", name: "Interval" },
      { letter: "T", name: "Sort Numbers" },
      { letter: "U", name: "Float or int" },
      { letter: "V", name: "Comparison" },
      { letter: "W", name: "Mathematical Expression" },
      { letter: "X", name: "Two intervals" },
      { letter: "Y", name: "The last 2 digits" },
      { letter: "Z", name: "Hard Compare" },
    ],
  },
  {
    id: "contest-1",
    name: "02. Contest #1",
    contestId: "219133",
    problems: [
      { letter: "A", name: "Winter Sale" },
      { letter: "B", name: "Memo and Momo" },
      { letter: "C", name: "Next Alphabet" },
      { letter: "D", name: "Ali Baba and Puzzles" },
      { letter: "E", name: "Interval Sweep" },
      { letter: "F", name: "Adding Bits" },
      { letter: "G", name: "Katryoshka" },
      { letter: "H", name: "Data Type Guessing" },
      { letter: "I", name: "Lucky Numbers" },
    ],
  },
  {
    id: "sheet-2",
    name: "03. Sheet #2 (Loops)",
    contestId: "219447",
    problems: [
      { letter: "A", name: "1 to N" },
      { letter: "B", name: "Even Numbers" },
      { letter: "C", name: "Even, Odd, Positive and Negative" },
      { letter: "D", name: "Fixed Password" },
      { letter: "E", name: "Max" },
      { letter: "F", name: "Multiplication table" },
      { letter: "G", name: "Factorial" },
      { letter: "H", name: "One Prime" },
      { letter: "I", name: "Palindrome" },
      { letter: "J", name: "Primes from 1 to n" },
      { letter: "K", name: "Divisors" },
      { letter: "L", name: "GCD" },
      { letter: "M", name: "Lucky Numbers" },
      { letter: "N", name: "Numbers Histogram" },
      { letter: "O", name: "Pyramid" },
      { letter: "P", name: "Shape1" },
      { letter: "Q", name: "Digits" },
      { letter: "R", name: "Sequence of Numbers and Sum" },
      { letter: "S", name: "Sum of Consecutive Odd Numbers" },
      { letter: "T", name: "Shape2" },
      { letter: "U", name: "Some Sums" },
      { letter: "V", name: "PUM" },
      { letter: "W", name: "Shape3" },
      { letter: "X", name: "Convert To Binary" },
      { letter: "Y", name: "Easy Fibonacci" },
      { letter: "Z", name: "Three Numbers" },
    ],
  },
  {
    id: "contest-2",
    name: "04. Contest #2",
    contestId: "219774",
    problems: [
      { letter: "A", name: "Timon and Pumbaa" },
      { letter: "B", name: "Drawing 'X'" },
      { letter: "C", name: "Finding Minimums" },
      { letter: "D", name: "Range Sum" },
      { letter: "E", name: "Hady Rides the Train" },
      { letter: "F", name: "Break Number" },
      { letter: "G", name: "Construct the Sum" },
      { letter: "H", name: "Simple Mod" },
    ],
  },
  {
    id: "sheet-3",
    name: "05. Sheet #3 (Arrays)",
    contestId: "219774",
    problems: [
      { letter: "A", name: "Summation" },
      { letter: "B", name: "Searching" },
      { letter: "C", name: "Replacement" },
      { letter: "D", name: "Positions in array" },
      { letter: "E", name: "Lowest Number" },
      { letter: "F", name: "Reversing" },
      { letter: "G", name: "Palindrome Array" },
      { letter: "H", name: "Sorting" },
      { letter: "I", name: "Smallest Pair" },
      { letter: "J", name: "Lucky Array" },
      { letter: "K", name: "Sum Digits" },
      { letter: "L", name: "Max Subarray" },
      { letter: "M", name: "Replace MinMax" },
      { letter: "N", name: "Check Code" },
      { letter: "O", name: "Fibonacci" },
      { letter: "P", name: "Minimize Number" },
      { letter: "Q", name: "Count Subarrays" },
      { letter: "R", name: "Permutation with arrays" },
      { letter: "S", name: "Search In Matrix" },
      { letter: "T", name: "Matrix" },
      { letter: "U", name: "Is B a subsequence of A?" },
      { letter: "V", name: "Frequency Array" },
      { letter: "W", name: "Mirror Array" },
      { letter: "X", name: "8 Neighbors" },
      { letter: "Y", name: "Range sum query" },
      { letter: "Z", name: "Binary Search" },
    ],
  },
  {
    id: "contest-3",
    name: "06. Contest #3",
    contestId: "326907",
    problems: [
      { letter: "A", name: "Square or rectangle" },
      { letter: "B", name: "Reversing" },
      { letter: "C", name: "Choose Elements" },
      { letter: "D", name: "Counting Elements" },
      { letter: "E", name: "Alternating Array" },
      { letter: "F", name: "Front - End" },
      { letter: "G", name: "Even Hate Odd" },
    ],
  },
  {
    id: "sheet-4",
    name: "07. Sheet #4 (Strings)",
    contestId: "219856",
    problems: [
      { letter: "A", name: "Create A New String" },
      { letter: "B", name: "Let's use Getline" },
      { letter: "C", name: "Compare" },
      { letter: "D", name: "Strings" },
      { letter: "E", name: "Count" },
      { letter: "F", name: "Way Too Long Words" },
      { letter: "G", name: "Conversion" },
      { letter: "H", name: "Good or Bad" },
      { letter: "I", name: "Palindrome" },
      { letter: "J", name: "Count Letters" },
      { letter: "K", name: "I Love strings" },
      { letter: "L", name: "String Functions" },
      { letter: "M", name: "Subsequence String" },
      { letter: "N", name: "Max Subsequence" },
      { letter: "O", name: "Sort String" },
      { letter: "P", name: "Count Words" },
      { letter: "Q", name: "Reverse Words" },
      { letter: "R", name: "String Score" },
      { letter: "S", name: "Max Split" },
      { letter: "T", name: "URL" },
      { letter: "U", name: "New Words" },
      { letter: "V", name: "Replace Word" },
      { letter: "W", name: "Encrypt & Decrypt Message" },
      { letter: "X", name: "Comparison" },
      { letter: "Y", name: "Min Cost String" },
      { letter: "Z", name: "Clean Code" },
    ],
  },
  {
    id: "sheet-5",
    name: "08. Sheet #5 (Functions)",
    contestId: "223205",
    problems: [
      { letter: "A", name: "Add" },
      { letter: "B", name: "Print" },
      { letter: "C", name: "Wonderful Number" },
      { letter: "D", name: "Prime Function" },
      { letter: "E", name: "Swap" },
      { letter: "F", name: "Equation" },
      { letter: "G", name: "Max and MIN" },
      { letter: "H", name: "N Times" },
      { letter: "I", name: "Swapping With Matrix" },
      { letter: "J", name: "Average" },
      { letter: "K", name: "Shift Right" },
      { letter: "L", name: "New Array" },
      { letter: "M", name: "Distinct Numbers" },
      { letter: "N", name: "Shift Zeros" },
      { letter: "O", name: "Five in One" },
    ],
  },
  {
    id: "sheet-6",
    name: "09. Sheet #6 (Math - Geometry)",
    contestId: "223338",
    problems: [
      { letter: "A", name: "Power Of Two" },
      { letter: "B", name: "Prime checking" },
      { letter: "C", name: "Sum of Range" },
      { letter: "D", name: "Xor" },
      { letter: "E", name: "Maximum Distinct Numbers" },
      { letter: "F", name: "Multiplication of Matrices" },
      { letter: "G", name: "Summation of its divisors" },
      { letter: "H", name: "GCD" },
      { letter: "I", name: "Divisibility" },
      { letter: "J", name: "Prime Factors" },
      { letter: "K", name: "Combination and Permutation" },
      { letter: "L", name: "Pascal Triangle" },
      { letter: "M", name: "Divisible" },
      { letter: "N", name: "Convert to Base" },
      { letter: "O", name: "Big Add and Multiply" },
      { letter: "P", name: "Factorial Digits" },
      { letter: "Q", name: "Product" },
      { letter: "R", name: "Distance points" },
      { letter: "S", name: "Is Triangle" },
      { letter: "T", name: "Circle Task" },
      { letter: "U", name: "Straight Line" },
      { letter: "V", name: "Two Lines" },
      { letter: "W", name: "Circles" },
      { letter: "X", name: "Rectangle" },
      { letter: "Y", name: "Common Area" },
      { letter: "Z", name: "Geometry Test" },
    ],
  },
  {
    id: "sheet-7",
    name: "10. Sheet #7 (Recursion)",
    contestId: "223339",
    problems: [
      { letter: "A", name: "Print Recursion" },
      { letter: "B", name: "Print from 1 to N" },
      { letter: "C", name: "Print from N to 1" },
      { letter: "D", name: "Print Digits using Recursion" },
      { letter: "E", name: "Base Conversion" },
      { letter: "F", name: "Print Even Indices" },
      { letter: "G", name: "Pyramid" },
      { letter: "H", name: "Inverted Pyramid" },
      { letter: "I", name: "Count Vowels" },
      { letter: "J", name: "Factorial" },
      { letter: "K", name: "Max Number" },
      { letter: "L", name: "Summation" },
      { letter: "M", name: "Suffix Sum" },
      { letter: "N", name: "Sum of a Matrix" },
      { letter: "O", name: "Fibonacci" },
      { letter: "P", name: "Log2" },
      { letter: "Q", name: "3n + 1 sequence" },
      { letter: "R", name: "Palindrome Array" },
      { letter: "S", name: "Array Average" },
      { letter: "T", name: "Combination" },
      { letter: "U", name: "Knapsack" },
      { letter: "V", name: "Creating Expression" },
      { letter: "W", name: "Reach Value" },
      { letter: "X", name: "The maximum path-sum" },
      { letter: "Y", name: "Number of Ways" },
      { letter: "Z", name: "Left-Max" },
    ],
  },
  {
    id: "sheet-8",
    name: "11. Sheet #8 (General easy)",
    contestId: "223206",
    problems: [
      { letter: "A", name: "Palindromes Replace" },
      { letter: "B", name: "Watermelon" },
      { letter: "C", name: "Koko And The Transformation" },
      { letter: "D", name: "Bear and Big Brother" },
      { letter: "E", name: "George and Accommodation" },
      { letter: "F", name: "Fox And Snake" },
      { letter: "G", name: "Magnets" },
      { letter: "H", name: "Presents" },
      { letter: "I", name: "Colorful Stones" },
      { letter: "J", name: "Lucky Division" },
      { letter: "K", name: "Prime Fibonacci" },
      { letter: "L", name: "Sereja and Dima" },
      { letter: "M", name: "The New Year: Meeting Friends" },
      { letter: "N", name: "Cakeminator" },
      { letter: "O", name: "Free Ice Cream" },
      { letter: "P", name: "Police Recruits" },
      { letter: "Q", name: "Night at the Museum" },
      { letter: "R", name: "Arrival of the General" },
      { letter: "S", name: "Good Number" },
      { letter: "T", name: "Helpful Maths" },
      { letter: "U", name: "Ilya and Bank Account" },
      { letter: "V", name: "Is it rated?" },
      { letter: "W", name: "Mahmoud and Longest Uncommon Subsequence" },
      { letter: "X", name: "Panoramix's Prediction" },
      { letter: "Y", name: "Team Olympiad" },
      { letter: "Z", name: "Decoding" },
    ],
  },
  {
    id: "sheet-9",
    name: "12. Sheet #9 (General medium)",
    contestId: "223207",
    problems: [
      { letter: "A", name: "Drawing Task" },
      { letter: "B", name: "Arpa's hard exam and Mehrdad's naive cheat" },
      { letter: "C", name: "Dragons" },
      { letter: "D", name: "Juicer" },
      { letter: "E", name: "Keyboard" },
      { letter: "F", name: "Puzzles" },
      { letter: "G", name: "Twins" },
      { letter: "H", name: "Launch of Collider" },
      { letter: "I", name: "Lineland Mail" },
      { letter: "J", name: "Shaass and Oskols" },
      { letter: "K", name: "Stars Drawing" },
      { letter: "L", name: "Announcement!" },
      { letter: "M", name: "!Palindromes" },
      { letter: "N", name: "Pumbaa And Apples" },
      { letter: "O", name: "Yaroslav and Permutations" },
      { letter: "P", name: "Calculating Function" },
      { letter: "Q", name: "Dreamoon and Stairs" },
      { letter: "R", name: "Ksenia and Pan Scales" },
      { letter: "S", name: "Mahmoud and a Triangle" },
      { letter: "T", name: "Olesya and Rodion" },
      { letter: "U", name: "T-primes" },
      { letter: "V", name: "Balanced Rating Changes" },
      { letter: "W", name: "Football" },
      { letter: "X", name: "Mountain Scenery" },
      { letter: "Y", name: "Polo the Penguin and Segments" },
      { letter: "Z", name: "Fraction" },
    ],
  },
  {
    id: "sheet-10",
    name: "13. Sheet #10 (General Hard)",
    contestId: "223719",
    problems: [
      { letter: "A", name: "Palindromes Replace" },
      { letter: "B", name: "Delete from the Left" },
      { letter: "C", name: "Koko And The Transformation" },
      { letter: "D", name: "Hussien and Strings" },
      { letter: "E", name: "Construct The Sum" },
      { letter: "F", name: "Marks" },
      { letter: "G", name: "Smallest Product" },
      { letter: "H", name: "Chewbacca and Number" },
      { letter: "I", name: "Coins" },
      { letter: "J", name: "Help Vasilisa the Wise 2" },
      { letter: "K", name: "Snacktower" },
      { letter: "L", name: "Two Squares" },
      { letter: "M", name: "Postcard" },
      { letter: "N", name: "Katryoshka" },
      { letter: "O", name: "Help Koko" },
      { letter: "P", name: "No Time for Dragons" },
      { letter: "Q", name: "Bulbs" },
      { letter: "R", name: "Cut Ribbon" },
      { letter: "S", name: "DZY Loves Chessboard" },
      { letter: "T", name: "Easter Eggs" },
      { letter: "U", name: "From S To T" },
      { letter: "V", name: "New Password" },
      { letter: "W", name: "Hussien and Arrays 2" },
      { letter: "X", name: "Strange Addition" },
      { letter: "Y", name: "Spiral" },
      { letter: "Z", name: "Triangle" },
    ],
  },
];
